[#3] Generate project from flutter-templates
nimblehq/ic-flutter-taher-toby pull request #45
Opened 2023-03-20 03:37 UTC by Tuubz

Closes: https://github.com/nimblehq/ic-flutter-taher-toby/issues/3

## What happened 👀

- Generate project from flutter-templates
- Update CODEOWNERS
- Update GitHub templates
- Update README.md
- Remove `story_template.md`

## Proof Of Work 📹

App can be built successfully: 

<img width="403" alt="Screen Shot 2023-03-20 at 10 36 15" src="https://user-images.githubusercontent.com/18277915/226240803-513e377c-0bf4-4432-9635-b80db66113cd.png">

2023-03-20 04:03 UTC, Tuubz commented
If I'm not mistaken, the Codecov warning is showing because there's currently no data in `develop` to compare with

2023-03-21 04:20 UTC, Shayokh144 approved these changes
looks good to me.

2023-03-21 10:06 UTC, luongvo requested changes
The rest lgtm

2023-03-21 10:06 UTC, luongvo commented on scripts/setup.py
We don't need this script in the generated project.

2023-03-21 10:06 UTC, luongvo commented on scripts/test.py
same

2023-03-21 10:26 UTC, Tuubz commented on scripts/test.py
@luongvo Updated 🚀

2023-03-21 10:32 UTC, luongvo approved these changes

2023-03-21 10:42 UTC, merged